import { QuizQuestion } from '../interface/interface';

export const quizData: QuizQuestion[] = [
  {
    number: 1,
    question: "What is the capital of France?",
    option1: "London",
    option2: "Berlin",
    option3: "Paris",
    option4: "Madrid",
    correctAnswer: "c",
  },
  {
    number: 2,
    question: "Which planet is known as the Red Planet?",
    option1: "Venus",
    option2: "Mars",
    option3: "Jupiter",
    option4: "Saturn",
    correctAnswer: "b",
  },
  {
    number: 3,
    question: "What is the largest ocean on Earth?",
    option1: "Atlantic Ocean",
    option2: "Indian Ocean",
    option3: "Arctic Ocean",
    option4: "Pacific Ocean",
    correctAnswer: "d",
  },
  {
    number: 4,
    question: "Who painted the Mona Lisa?",
    option1: "Vincent van Gogh",
    option2: "Leonardo da Vinci",
    option3: "Pablo Picasso",
    option4: "Michelangelo",
    correctAnswer: "b",
  },
  {
    number: 5,
    question: "What is the smallest prime number?",
    option1: "0",
    option2: "1",
    option3: "2",
    option4: "3",
    correctAnswer: "c",
  },
  {
    number: 6,
    question: "Which programming language is known for web development?",
    option1: "Python",
    option2: "JavaScript",
    option3: "C++",
    option4: "Java",
    correctAnswer: "b",
  },
  {
    number: 7,
    question: "What year did World War II end?",
    option1: "1943",
    option2: "1944",
    option3: "1945",
    option4: "1946",
    correctAnswer: "c",
  },
  {
    number: 8,
    question: "What is the chemical symbol for gold?",
    option1: "Go",
    option2: "Gd",
    option3: "Au",
    option4: "Ag",
    correctAnswer: "c",
  },
  {
    number: 9,
    question: "Which country is home to the kangaroo?",
    option1: "New Zealand",
    option2: "Australia",
    option3: "South Africa",
    option4: "Brazil",
    correctAnswer: "b",
  },
  {
    number: 10,
    question: "What is the speed of light in vacuum?",
    option1: "299,792 km/s",
    option2: "150,000 km/s",
    option3: "500,000 km/s",
    option4: "100,000 km/s",
    correctAnswer: "a",
  },
]
